### ISSUE TITLE
New Device: Delta Pro

### ISSUE THREAD

**Issue by PietroLubini** [PietroLubini/homebridge-ecoflow#21]
### Device

Delta Pro

### Characteristics

| Service    | Characteristic        | Standard | Permission |
| ---------- | --------------------- | -------- | ---------- |
| Battery    | BatteryLevel          | ✅       | Read       |
| Battery    | ChargingState         | ✅       | Read       |
| Battery    | StatusLowBattery      | ✅       | Read       |
| Outlet AC  | On                    | ✅       | Read/Write |
| Outlet AC  | OutletInUse           | ✅       | Read       |
| Outlet AC  | Battery Level, %      | 🔲       | Read       |
| Outlet AC  | Input Consumption, W  | 🔲       | Read       |
| Outlet AC  | Output Consumption, W | 🔲       | Read       |
| Outlet CAR | On                    | ✅       | Read/Write |
| Outlet CAR | OutletInUse           | ✅       | Read       |
| Outlet CAR | Battery Level, %      | 🔲       | Read       |
| Outlet CAR | Input Consumption, W  | 🔲       | Read       |
| Outlet CAR | Output Consumption, W | 🔲       | Read       |
| Outlet USB | On                    | ✅       | Read/Write |
| Outlet USB | OutletInUse           | ✅       | Read       |
| Outlet USB | Battery Level, %      | 🔲       | Read       |
| Outlet USB | Input Consumption, W  | 🔲       | Read       |
| Outlet USB | Output Consumption, W | 🔲       | Read       |
| Switch X-Boost | On                    | ✅       | Read/Write |

### Are you ready to test beta version of plugin with added device support?

🔴 No (please explain in the 'More Information' box below)

### More Information

Have no device to test on. Can test only in `Simulate` mode

**Comment by Vadimkin** [comment]
Hi Pietro,

Thanks for working on this integration! We have massive power outages in my country, so I want to make the HomeKit-integration to disable our electric kettle if we're on ecoflow, and it looks like mostly it works :)

The only major change I made – I added extra check if `data` is non-undefined: https://github.com/Vadimkin/homebridge-ecoflow/commit/af8f0f0d1e8aa26ac25b146575f6975953b2ef55#diff-7c50714ede734c9092354e5cb3cb81c2512b1fb13f4ba0d0eb42ea63e51f7cc2R62

When plugin is initialized, for the first message I have an event with all proper messages, but after that I see a lot of errors in the terminal. 

I added logger (you can see it in the diff), so some examples how it looks at some time:
```
processQuotaMessage {
  addr: 0,
  cmdFunc: 0,
  cmdId: 0,
  id: 1874877421204437000,
  version: '1.0',
  timestamp: 1733000458962,
  params: {
    'bmsMaster.temp': 29,
    'bmsMaster.inputWatts': 0,
    'bmsMaster.outputWatts': 0,
    'bmsMaster.soc': 89
  }
}
```

```
processQuotaMessage {
  addr: 0,
  cmdFunc: 0,
  cmdId: 0,
  id: 1874877429794344700,
  version: '1.0',
  timestamp: 1733000459118,
  params: {
    'ems.maxChargeSoc': 90,
    'ems.maxCloseOilEbSoc': 100,
    'ems.minDsgSoc': 0,
    'ems.minOpenOilEbSoc': 0
  }
}
```

Stack trace (my initial idea is that `updateInitialValues()` has different type of fields, but it looks some other case):
```
[30/11/2024, 23:01:07] TypeError: Cannot read properties of undefined (reading 'bmsMaster')
    at DeltaProAccessory.processQuotaMessage (/var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/src/accessories/batteries/deltapro/deltaProAccessoryBase.ts:63:14)
    at Object.next (/var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/src/apis/containers/mqttDevice.ts:42:49)
    at ConsumerObserver.next (/var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/node_modules/rxjs/src/internal/Subscriber.ts:161:25)
    at SafeSubscriber.Subscriber._next (/var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/node_modules/rxjs/src/internal/Subscriber.ts:119:22)
    at SafeSubscriber.Subscriber.next (/var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at /var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/node_modules/rxjs/src/internal/Subject.ts:68:20
    at Object.errorContext (/var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)
    at Subject.next (/var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/node_modules/rxjs/src/internal/Subject.ts:61:5)
    at MqttDevice.processReceivedMessage (/var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/src/apis/containers/mqttDevice.ts:26:27)
    at /var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/src/apis/ecoFlowMqttApiManager.ts:138:38
```

I'll test it more and will put my updates here. Thanks again for this enormous set of work!

**Comment by PietroLubini** [comment]
> Hi Pietro,
> 
> Thanks for working on this integration! We have massive power outages in my country, so I want to make the HomeKit-integration to disable our electric kettle if we're on ecoflow, and it looks like mostly it works :)
> 
> The only major change I made – I added extra check if `data` is non-undefined: [Vadimkin@af8f0f0#diff-7c50714ede734c9092354e5cb3cb81c2512b1fb13f4ba0d0eb42ea63e51f7cc2R62](https://github.com/Vadimkin/homebridge-ecoflow/commit/af8f0f0d1e8aa26ac25b146575f6975953b2ef55#diff-7c50714ede734c9092354e5cb3cb81c2512b1fb13f4ba0d0eb42ea63e51f7cc2R62)
> 
> When plugin is initialized, for the first message I have an event with all proper messages, but after that I see a lot of errors in the terminal.
> 
> I added logger (you can see it in the diff), so some examples how it looks at some time:
> 
> ```
> processQuotaMessage {
>   addr: 0,
>   cmdFunc: 0,
>   cmdId: 0,
>   id: 1874877421204437000,
>   version: '1.0',
>   timestamp: 1733000458962,
>   params: {
>     'bmsMaster.temp': 29,
>     'bmsMaster.inputWatts': 0,
>     'bmsMaster.outputWatts': 0,
>     'bmsMaster.soc': 89
>   }
> }
> ```
> 
> ```
> processQuotaMessage {
>   addr: 0,
>   cmdFunc: 0,
>   cmdId: 0,
>   id: 1874877429794344700,
>   version: '1.0',
>   timestamp: 1733000459118,
>   params: {
>     'ems.maxChargeSoc': 90,
>     'ems.maxCloseOilEbSoc': 100,
>     'ems.minDsgSoc': 0,
>     'ems.minOpenOilEbSoc': 0
>   }
> }
> ```
> 
> Stack trace (my initial idea is that `updateInitialValues()` has different type of fields, but it looks some other case):
> 
> ```
> [30/11/2024, 23:01:07] TypeError: Cannot read properties of undefined (reading 'bmsMaster')
>     at DeltaProAccessory.processQuotaMessage (/var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/src/accessories/batteries/deltapro/deltaProAccessoryBase.ts:63:14)
>     at Object.next (/var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/src/apis/containers/mqttDevice.ts:42:49)
>     at ConsumerObserver.next (/var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/node_modules/rxjs/src/internal/Subscriber.ts:161:25)
>     at SafeSubscriber.Subscriber._next (/var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/node_modules/rxjs/src/internal/Subscriber.ts:119:22)
>     at SafeSubscriber.Subscriber.next (/var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
>     at /var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/node_modules/rxjs/src/internal/Subject.ts:68:20
>     at Object.errorContext (/var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)
>     at Subject.next (/var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/node_modules/rxjs/src/internal/Subject.ts:61:5)
>     at MqttDevice.processReceivedMessage (/var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/src/apis/containers/mqttDevice.ts:26:27)
>     at /var/lib/homebridge/node_modules/@pietrolubini/homebridge-ecoflow/src/apis/ecoFlowMqttApiManager.ts:138:38
> ```
> 
> It looks that also it works now for initial state, but not with updates...
> 
> I'll test it more and will put my updates here. Thanks again for this enormous set of work!

Hi, does plugin works for your Delta Pro?

**Comment by PietroLubini** [comment]
Test Cases

|Description|Expected|
|-----|-----|
|Restart homebridge|The state of AC, DC 12V, USB, X-Boost, Battery level correpond to the ones in Ecoflow app|
|Check Battery level of main block without additional battery in HomeKit|Should be the same as inside Ecoflow app|
|Check Battery level of main block with additional battery (if there is any) in HomeKit|Should be the same as inside Ecoflow app|
|Unplug battery and check Charging State of one of outlets in HomeKit|Should show charging: No|
|Plug in battery and check Charging State of one of outlets in HomeKit|Should show charging: Yes|
|Turn on AC in Homekit| Real AC should be turned on|
|Plugin some device to AC and turn it on|AC Power Socket in use should be Yes|
|Turn off all devices that are plugged in to AC|AC Power Socket in use should be No|
|Plugin some device to AC and turn it on|AC Output Consumption should show Watts (in [Eve](https://apps.apple.com/us/app/eve-for-matter-homekit/id917695792) application) that corresponds to value inside EcoFlow app for AC|
|Turn on USB in Homekit| Real USB should be turned on|
|Plugin some device to USB and turn it on|USB Power Socket in use should be Yes|
|Turn off all devices that are plugged in to USB|USB Power Socket in use should be No|
|Plugin some device to USB and turn it on|USB Output Consumption should show Watts (in [Eve](https://apps.apple.com/us/app/eve-for-matter-homekit/id917695792) application) that corresponds to value inside EcoFlow app for USB|
|Turn on DC 12V in Homekit| Real DC 12V should be turned on|
|Plugin some device to DC 12V and turn it on|DC 12V' Power Socket in use should be Yes|
|Turn off all devices that are plugged in to DC 12V|DC 12V' Power Socket in use should be No|
|Plugin some device to DC 12V and turn it on|DC 12V' Output Consumption should show Watts (in [Eve](https://apps.apple.com/us/app/eve-for-matter-homekit/id917695792) application) that corresponds to value inside EcoFlow app for DC|
|Turn on X-Boost inside HomeKit|X-Boost is turned on in Ecoflow app|
|Turn on X-Boost inside Ecoflow app|X-Boost is turned on in Homekit|
|Turn on AC inside Ecoflow app|AC is turned on in Homekit|
|Turn on USB inside Ecoflow app|USB is turned on in Homekit|
|Turn on DC 12V inside Ecoflow app|DC 12V is turned on in Homekit|
